### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by HubertOehm** [jagenjo/webglstudio.js#15]
Hi!

Congratulations to WebGLStudio! Very impressive work!

Is it possible to make the background of a scene transparent? I want to composite 3d object I am building with WebGLStudio on top of web pages.

Hubert

**Comment by jagenjo** [comment]
Thanks!

Right now no, you can't because I create the WebGLContext without alpha but I will consider it for the next version.

**Comment by HubertOehm** [comment]
Wow! Thanks for the quick reply.

Yeah, I thought that this would be the case. Thank you for considering this
feature.

Best regards,
    Hubert

**Comment by jjkilpatrick** [comment]
Any update on this @jagenjo?

**Comment by jagenjo** [comment]
The problem is that using alpha in the context would mean the performance is a little slower, and this feature is not widely used.

However, when creating the LS.Player you can pass the property: ```{ alpha: true, premultipliedAlpha: false }``` so it will have the transparency on. This means that only will work in your environment, not in the editor.

But then I realized that you will need to set up the camera alpha to 0, which I never considered, so I had added a checkbox in the camera options to set the alpha to 0 (Bg.Alpha)

Just uploaded a version, you can test it latest:
http://webglstudio.org/latest/

Sorry for the delay.

**Comment by jjkilpatrick** [comment]
Thanks for such a speedy reply. I'll give it a test now
